apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-app
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: fortune-app
        env:
        - name: SPRING_REDIS_HOST
          value: "10.0.0.132"