apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-app
  template:
    metadata:
      name: fortune-app
      labels:
        app: fortune-app
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - image: harbor.sharedsvc.home.kwpivotal.com/apprepo/fortune-demo@sha256:b738a9368d1716c837d5e53b0900d9765af96a8800ac5113ee0d2e4c2a3f20fc
        name: fortune-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_REDIS_HOST
          value: 10.0.0.132
        - name: SPRING_REDIS_PORT
          value: '6379'
