apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-app
  template:
    metadata:
      name: fortune-app
      labels:
        app: fortune-app
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - image: harbor.sharedsvc.home.kwpivotal.com/apprepo/fortune-demo@sha256:74dd9551ea7a2148fecb915b92904a65fbf0b6ed7019c21c9304eeefd4034966
        name: fortune-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_REDIS_HOST
          value: 10.0.0.132
        - name: SPRING_REDIS_PORT
          value: '6379'
